#!/bin/bash
# Configure libvirtd for remote SSH access
# This script modifies /etc/libvirt/libvirtd.conf to enable remote management

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=== libvirtd Remote Access Configuration ==="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
    exit 1
fi

# Check if libvirtd is installed
if ! command -v virsh &> /dev/null; then
    echo -e "${RED}Error: libvirt is not installed${NC}"
    exit 1
fi

LIBVIRT_CONF="/etc/libvirt/libvirtd.conf"
BACKUP_CONF="${LIBVIRT_CONF}.backup.$(date +%Y%m%d-%H%M%S)"

# Backup existing config
echo "Backing up existing configuration to: $BACKUP_CONF"
cp "$LIBVIRT_CONF" "$BACKUP_CONF"

# Check if already configured
if grep -q "^listen_tls = 0" "$LIBVIRT_CONF" 2>/dev/null; then
    echo -e "${YELLOW}Warning: Configuration may already be set${NC}"
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 0
    fi
fi

echo "Configuring libvirtd for remote SSH access..."

# Create new configuration
cat > "$LIBVIRT_CONF" << 'EOF'
# libvirtd.conf - Remote access via SSH (qemu+ssh://)
# Generated by kubernetes-platform-infrastructure configure-libvirt-remote.sh

# Disable TLS/TCP (we use SSH for security)
listen_tls = 0
listen_tcp = 0

# Unix socket configuration
unix_sock_group = "libvirt"
unix_sock_ro_perms = "0777"
unix_sock_rw_perms = "0770"

# Access control
access_drivers = [ "polkit" ]

# Logging
log_filters="3:remote 4:event"
log_outputs="3:syslog:libvirtd"

# Keep alive (prevents SSH timeouts)
keepalive_interval = 5
keepalive_count = 5

# Performance
max_clients = 20
max_queued_clients = 1000
max_workers = 20
max_requests = 20
prio_workers = 5
EOF

echo -e "${GREEN}✓ Configuration written${NC}"

# Ensure current user is in libvirt group
CURRENT_USER=${SUDO_USER:-$USER}
if ! groups "$CURRENT_USER" | grep -q libvirt; then
    echo "Adding $CURRENT_USER to libvirt group..."
    usermod -aG libvirt "$CURRENT_USER"
    echo -e "${YELLOW}Note: User must log out and back in for group changes to take effect${NC}"
fi

# Restart libvirtd
echo "Restarting libvirtd..."
systemctl restart libvirtd

if systemctl is-active --quiet libvirtd; then
    echo -e "${GREEN}✓ libvirtd restarted successfully${NC}"
else
    echo -e "${RED}Error: libvirtd failed to start${NC}"
    echo "Restoring backup..."
    cp "$BACKUP_CONF" "$LIBVIRT_CONF"
    systemctl restart libvirtd
    exit 1
fi

echo ""
echo "=== Configuration Complete ==="
echo ""
echo "Test remote access from your laptop with:"
echo "  virsh -c qemu+ssh://${CURRENT_USER}@$(hostname -I | awk '{print $1}')/system list --all"
echo ""
echo "Backup saved to: $BACKUP_CONF"
